# Generated by Django 4.0.2 on 2022-02-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
