# Generated by Django 4.0.2 on 2022-03-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-begin',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
