# Generated by Django 4.0.2 on 2022-03-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_subscription_options_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
