# Generated by Django 4.0.2 on 2022-02-21 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-publish',), 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='publish',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Опубликовано'),
        ),
    ]
