# Generated by Django 4.0.2 on 2022-03-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена за год')),
                ('price_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена за месяц')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ('price_year', 'price_month'),
            },
        ),
    ]
