# Generated by Django 4.0.2 on 2022-03-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('archive', 'Архивный')], default='active', max_length=8, verbose_name='Статус'),
        ),
    ]
