# Generated by Django 4.0.2 on 2022-02-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема')),
                ('status', models.CharField(choices=[('Новая заявка', 'Новая заявка'), ('На рассмотрении', 'На рассмотрении'), ('В работе', 'В работе'), ('Завершено', 'Завершено')], default='Новая заявка', max_length=50, verbose_name='Статус')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=10, null=True, verbose_name='Дом')),
                ('apartment', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Квартира')),
                ('body', models.TextField(verbose_name='Что случилось')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ('-updated',),
            },
        ),
    ]
