# Generated by Django 4.0.2 on 2022-03-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='body',
            field=models.TextField(max_length=500, verbose_name='Что случилось'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
    ]
